---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php support packages for Debian and Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

 - name: Install apache/httpd and php support packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes 
   when: ansible_distribution == "CentoS"
