---

# This play installs all updates first
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian and Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentoS"

# This play installs apache and php support on all hosts identified as web servers
- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php support packages for Debian and Ubuntu
    tags: apache,apache2,Debian,Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install apache or httpd and php support packages for CentOS
    tags: apache,apache2,CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest 
    when: ansible_distribution == "CentoS"

# This play installs mariaDB on all hosts identified as DB servers
- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb packages for Debian and Ubuntu
    tags: mariadb,mariadb-server,Debian,Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install mariadb packages for CentOS
    tags: mariadb,CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentoS"

# This play install samba on all hosts identified as file servers, incomplete
- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package: 
      name: samba
      state: latest

