---

# This play installs all updates first
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian and Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentoS"

# This play adds the ann (ansible) user and ssh key
- hosts: all
  become: true
  tasks:
    
  - name: Create user ann
    tags: always
    user:
      name: ann
      groups: root

  - name: Add ssh key for ann
    tags: always
    authorized_key:
      user: ann
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII8wkSZmxGCLrBxD2vaIpa+Ljda1xUROvc05zan+DvUj ansible default"

  - name: Add sudoers file for ann
    tags: always
    copy:
      src: sudoer_ann
      dest: /etc/sudoers.d/ann
      owner: root
      group: root
      mode: 0440


# This sets up terraform on new workstations
- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package: 
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

# This play installs apache and php support on all hosts identified as web servers
- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php support packages for Debian and Ubuntu
    tags: apache,apache2,Debian,Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install apache or httpd and php support packages for CentOS
    tags: apache,httpd,CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest 
    when: ansible_distribution == "CentoS"

# This play starts and enables the httpd service on CentOS web_servers
  - name: Start httpd on CentOS web_servers
    tags: apache,httpd,CentOS
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentoS"


# This installs the default website file. Directory 'files' is assumed
  - name: Copy default html file for website
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

# This play installs mariaDB on all hosts identified as DB servers
- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb packages for Debian and Ubuntu
    tags: mariadb,mariadb-server,Debian,Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install mariadb packages for CentOS
    tags: mariadb,CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentoS"

# This play install samba on all hosts identified as file servers, incomplete
- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package: 
      name: samba
      state: latest

